apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memora.fullname" . }}-config
  labels:
    {{- include "memora.labels" . | nindent 4 }}
data:
  # API configuration
  llm-provider: {{ .Values.api.env.MEMORA_API_LLM_PROVIDER | quote }}
  llm-model: {{ .Values.api.env.MEMORA_API_LLM_MODEL | quote }}

  # Control plane configuration
  node-env: {{ .Values.controlPlane.env.NODE_ENV | quote }}
  hostname: {{ .Values.controlPlane.env.MEMORA_CP_HOSTNAME | quote }}
  control-plane-port: {{ .Values.controlPlane.env.MEMORA_CP_PORT | quote }}
