{{- if .Values.controlPlane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memora.fullname" . }}-control-plane
  labels:
    {{- include "memora.controlPlane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
  - port: {{ .Values.controlPlane.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "memora.controlPlane.selectorLabels" . | nindent 4 }}
{{- end }}
