apiVersion: v2
name: hindsight
description: Hindsight helm chart
type: application
version: 0.1.5
appVersion: "0.1.5"
keywords:
  - ai
  - memory
  - llm
  - agents
maintainers:
  - name: Hindsight Team
